//Authentication
//Register
export const REGISTER_API_START = "REGISTER_API_START";
export const REGISTER_API_SUCCESS = " REGISTER_API_SUCCESS";
export const REGISTER_API_FAIL = " REGISTER_API_FAIL";
//Login
export const LOGIN_API_START = "LOGIN_API_START";
export const LOGIN_API_SUCCESS = " LOGIN_API_SUCCESS";
export const LOGIN_API_FAIL = " LOGIN_API_FAIL";
//Logout
export const LOGOUT_API_START = "LOGOUT_API_START";
export const LOGOUT_API_SUCCESS = " LOGOUT_API_SUCCESS";
export const LOGOUT_API_FAIL = " LOGOUT_API_FAIL";
//refreshToken
export const REFRESH_TOKEN_START = "REFRESH_TOKEN_START";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";
//Profile
export const GET_PROFILE_START = "GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const CLEAR_ERRORS_SUCCESS = "CLEAR_ERRORS_SUCCESS";


//Product
export const GET_PRODUCT_START = "GET_PRODUCT_START";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
//get1 product
export const GET_ONE_PRODUCT_START = "GET_ONE_PRODUCT_START";
export const GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS";
export const GET_ONE_PRODUCT_FAIL = "GET_ONE_PRODUCT_FAIL";